### ISSUE TITLE
Difference in the paper and code implementation about agents encoding

### ISSUE THREAD

**Issue by ultimatedigiman** [nachiket92/PGP#1] opened 2021-12-12 07:35 UTC
Hi

First of all, thank you for sharing the code, which is very helpful to the community!

When I'm reading your code, I found a major difference between the code implementation and the paper: the encoding process of surrounding agents.

* **the paper**
Both raw feature of vehicles and pedestrians are **s_t^i** which including an indicator **I^i** with value 1 for a pedestrian and 0 for a vehicle
<img width="706" alt="image" src="https://user-images.githubusercontent.com/67790229/145703980-e3150992-fa97-487f-9b9a-d8ef04448f5b.png">

And you use the same GRU to encode both vehicles and pedestrians
So there are **3** GRUs in total: one for lane nodes, one for target agent, and one for surrounding agents

<img width="712" alt="image" src="https://user-images.githubusercontent.com/67790229/145704027-8ac2fe63-7076-41ae-b112-0d3dd111ea54.png">
but the code implementation is different

* **Code**
There is no indicator in the raw feature of vehicles and pedestrians
And you use 2 independent GRUs to encode vehicles and pedestrians:

https://github.com/nachiket92/PGP/blob/eb24e1904d4eae15200a02089992718aeb7a8149/models/encoders/pgp_encoder.py#L47-L51

then cat them together:
https://github.com/nachiket92/PGP/blob/eb24e1904d4eae15200a02089992718aeb7a8149/models/encoders/pgp_encoder.py#L119

So there are **4** GRUs in total: one for lane nodes, one for target agent,  one for surrounding vehicles and one for surrounding pedestrians

-----------------------
They are two different encoding methods, have you tried both? And what's the reason for choosing the latter?

Many greetings

**Comment by nachiket92** [comment] 2021-12-13 20:39
Thanks for bringing this up. This was an oversight on my part while re-implementing. For what it's worth, the results are practically the same. This is what I got.


With separate encoders for surrounding pedestrians and vehicles. Use main branch and [trained weights](https://drive.google.com/file/d/13In9e3otlGmqKEnzhj2s0SFKXOesi05t/view?usp=sharing) to reproduce.

MinADE_5:  1.30
MinADE_10:  0.97
MissRate_5:  0.54
MissRate_10:  0.35
MinFDE_1:  7.50
Off-road rate:  0.03


With common encoder and indicator feature, as per the paper. Use branch nbr_enc_issue1 and [trained weights](https://drive.google.com/file/d/17VBWQkiO_D7jubR8GmaPTdaJpSvlqY70/view?usp=sharing) to reproduce. 

MinADE_5:  1.30
MinADE_10:  0.97
MissRate_5:  0.54
MissRate_10:  0.35
MinFDE_1:  7.34
Off-road rate:  0.02  

Since the common encoder model achieves comparable performance with fewer parameters and matches the paper, I'll merge the branch shortly.

**Comment by ultimatedigiman** [comment] 2021-12-13 22:11
Are these weights pre-trained using the ground truth traversal for some epochs or just trained from scratch with random traversals?

**Comment by nachiket92** [comment] 2021-12-13 22:18
Both trained from scratch. Turns out this works just fine, and also simplifies training.  

If you do want to pretrain the model with ground truth traversals, set the 'pre_train' flag to true in the aggregator parameters in the config file, on line 48.

**Comment by ultimatedigiman** [comment] 2021-12-13 22:28
Thanks for the quick response.

**Comment by nachiket92** [comment] 2021-12-13 22:31
I'm merging the PR and closing the issue. Thanks again!

**Closed as completed by nachiket92** 2021-12-13 22:31 UTC
